blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("post/<slug:slug>/", views.DetailPostView.as_view(), name="post_detail"),
    path("tag/<slug:tag>/", views.TagListView.as_view(), name="post_by_tag"),
]

djblogger/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager


class Post(models.Model):
    choices = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(
        max_length=100, unique=True, validators=[MinLengthValidator(3)]
    )
    subtitle = models.CharField(
        max_length=100, unique=True, validators=[MinLengthValidator(3)]
    )
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="post_author"
    )
    content = models.TextField(validators=[MinLengthValidator(5)])
    status = models.CharField(max_length=10, choices=choices, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    class Meta:
        ordering = ["-created_at"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic

from .models import Post


class HomeView(generic.ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    paginate_by = 10

    def get_template_names(self):
        if self.request.htmx:
            return ["blog/components/post-list-elements.html"]
        return ["blog/home.html"]


class DetailPostView(generic.DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    lookup_field = "slug"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_posts = Post.objects.filter(author=self.object.author)[:5]
        context['author_posts'] = author_posts
        return context


class TagListView(generic.ListView):
    model = Post
    template_name = 'blog/tags.html'
    paginate_by = 10
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get("tag"))

    def get_template_names(self):
        if self.request.htmx:
            return ["blog/components/post-list-elements-tags.html"]
        return ["blog/tags.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs.get("tag")
        return context

djblogger/templates/3-col-template.html
{% extends 'base.html' %}
{% block content %}
<style>
  @media only screen and (min-width: 992px) {
    .col-navbar {
      flex: 0 0 80px;
      display: flex;
      justify-content: center;
      border-right: 1px solid whitesmoke;
      height: 100vh;
    }
  }

</style>
<div class="container" style="max-width: 1500px!important;">
  <div class="row">
    <div class="col-navbar">
      {% block content-left %}
      {% endblock content-left %}
    </div>
    <div class="col-12 col-lg-8 pt-5 px-4 px-md-5">
      {% block content-mid %}
      {% endblock content-mid %}
    </div>
    <div class="d-none d-lg-block col-lg-3 pt-5 border-start ps-4">
      {% block content-right %}
      {% endblock content-right %}
      {% include 'footer.html' %}
    </div>
  </div>
</div>
{% endblock content %}

djblogger/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@900&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;900&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
  {% block navbar %}
  {% include 'navbar.html' %}
  {% include './blog/components/splash.html' %}
  {% endblock navbar %}
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@1.8.6"
    integrity="sha384-Bj8qm/6B+71E6FQSySofJOUjA/gq330vEqjFx9LakWybUySyI1IQHwPtbTU7bNwx"
    crossorigin="anonymous"></script>
</body>

</html>

djblogger/templates/blog/components/post-list-elements-tags.html
<style>
  p {
    font-family: 'Merriweather', sans-serif;
    line-height: 22px;
  }

</style>
{% for post in posts %}
<a class="text-decoration-none" href="{% url 'blog:post_detail' post.slug %}">
  {% if forloop.last %}
  <div class="card border-0 pb-3 pb-sm-5" hx-trigger="revealed"
    hx-get="{{ request.path }}?page={{ page_obj.number|add:1 }}" hx-swap=" afterend">
    {% else %}
    <div class="card border-0 pb-3 pb-sm-5">
      {% endif %}
      <div class="row">
        <div class="col-9">
          <div class="card-body p-0">
            <div class="pb-2 text-body infinite-scroll-author small">{{ post.author }}</div>
            <h1 class="mb-1 fs-4 text-body fw-bold infinite-scroll-title">{{ post.title|truncatechars:80 }}</h1>
            <p class="text-dark d-none d-md-block fs-14">{{ post.content|truncatechars:180 }}</p>
          </div>
        </div>
        <div class="col-3">
          <img src="https://picsum.photos/112/112" alt="Image of {{ post.title }}" class="img-fluid float-end" />
        </div>
      </div>
    </div>
</a>
{% endfor %}

djblogger/templates/blog/components/post-list-elements.html
{% for post in posts %}
<a class="text-decoration-none" href="{% url 'blog:post_detail' post.slug %}">
  {% if forloop.last %}
  <div class="card border-0 pb-3 pb-sm-5" hx-trigger="revealed"
    hx-get="{% url 'blog:home' %}?page={{ page_obj.number|add:1 }}" hx-swap="afterend">
    {% else %}
    <div class="card border-0 pb-3 pb-sm-5">
      {% endif %}
      <div class="row">
        <div class="col-8">
          <div class="card-body p-0">
            <div class="pb-2 text-body infinite-scroll-author">{{ post.author }}</div>
            <h1 class="mb-1 fs-4 text-body fw-bold infinite-scroll-title">{{ post.title|truncatechars:80 }}</h1>
            <h2 class="text-muted fs-6 d-none d-md-block">{{ post.subtitle }}</h2>
            <div class="text-muted infinite-scroll-date">{{ post.updated_at|date:"M d" }}</div>
          </div>
        </div>
        <div class="col-4">
          <img src="https://picsum.photos/205/115" alt="Image of {{ post.title }}" class="img-fluid float-end" />
        </div>
      </div>
    </div>
</a>
{% endfor %}

djblogger/templates/blog/components/splash.html
<div class="border-bottom border-2 border-dark">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 py-1 py-md-5 text-center text-md-start">
        <h1 class="display-1">Tech Talk.</h1>
        <p class="fs-4 lh-1 text-muted fw-500 pb-5">
          No nonsense tutorials, tups, and expertise from writers on tech
          topics.
        </p>
        <button type="button" class="btn btn-dark rounded-pill fw-500 fs-5 px-4">Start reading</button>
      </div>
    </div>
  </div>
</div>

djblogger/templates/blog/components/tag-cloud.html
<div class="mb-4">
    <div class="border-bottom">
        <div class="pb-4">
            <h4 class="pb-2 fw-bold fs-14">{{ 'discover more of what matters to you'|upper }}</h4>
            {% for tag in tags %}
                <span class="border border-dark p-1 px-3 mb-2 me-1 rounded-pill"
                      style="display: inline-block">
                    <a href="{% url 'blog:post_by_tag' tag.slug %}"
                       class="fs-15 fw-500 text-decoration-none text-black">{{ tag.name }}</a>
                </span>
            {% endfor %}
        </div>
    </div>
</div>

djblogger/templates/blog/home.html
{% extends 'base.html' %}
{% block title %}
Welcome to the Blog Home
{% endblock title %}
{% block content %}
<div class="container pt-5">
  <div class="row">
    <div class="col-12 col-lg-8">{% include 'blog/components/post-list-elements.html' %}</div>
    <div class="d-none d-lg-block col-4">
      {% sidebar_tag_cloud %}
      {% include 'footer.html' %}
    </div>
  </div>
</div>
{% endblock content %}

djblogger/templates/blog/post_detail.html
{% extends '3-col-template.html' %}
{% block title %}
Detail of {{ post.title }}
{% endblock title %}
{% block navbar %}
{% endblock navbar %}
{% block content-left %}
{% include 'secondary-navbar.html' %}
{% endblock content-left %}
{% block content-mid %}
<style>
  .blogger h1 {
    letter-spacing: -0.6px;
  }

  .post h1 {
    font-size: 24px;
  }

  .post p {
    font-family: Merriweather, Arial;
    font-size: 1.0625rem;
    line-height: 32px;
    letter-spacing: 0.2px;
  }

</style>
<div class="blogger center mx-auto" style="max-width: 683px">
  <div class="text-muted">{{ post.author }}</div>
  <div class="text-muted">{{ post.updated_at|date:"M d" }}</div>
  <h1 class="fw-bold pb-2">{{ post.title }}</h1>
  <h2 class="text-muted fs-4 pb-4">{{ post.subtitle }}</h2>
  <div class="post fw-bold">
    <p>{{ post.content|markdown|safe }}</p>
  </div>
</div>
{% endblock content-mid %}
{% block content-right %}
{% sidebar_tag_cloud %}
<div class="col-12">
  <div>
    <div class="pb-3">More from {{ post.author }}</div>
    {% for post in author_posts %}
    <a href="{% url 'blog:post_detail' post.slug %}" class="text-decoration-none">
      <div class="card mb-3 border-0 ps-1">
        <div class="row">
          <div class="col-9 pe-2">
            <span class="text-dark small fw-bold">{{ post.author }}</span>
            <h1 class="mb-1 fs-6 p-0 text-dark">{{ post.title|truncatechars:80 }}</h1>
          </div>
          <div class="col-3">
            <img src="https://picsum.photos/205/115" alt="Image of {{ post.title }}" class="img-fluid float-end" />
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock content-right %}

djblogger/templates/blog/tags.html
{% extends '3-col-template.html' %}
{% block title %}
{% endblock title %}
{% block navbar %}
{% endblock navbar %}
{% block content-left %}
{% include 'secondary-navbar.html' %}
{% endblock content-left %}
{% block content-mid %}
<div style="max-width: 683px;" class="mx-auto">
  <h1 class="fs-1 fw-bold pb-5">{{ tag|title }}</h1>
  {% include 'blog/components/post-list-elements-tags.html' %}
</div>
{% endblock content-mid %}
{% block content-right %}
{% sidebar_tag_cloud %}
{% endblock content-right %}

djblogger/templates/footer.html
<style>
  .footer .nav-link {
    padding: 0 10px 5px 0;
  }

  .footer a {
    color: inherit;
  }

</style>
<footer>
  <ul class="nav fw-500 fs-12 footer">
    <li class="nav-item">
      <a href="#" class="nav-link">Help</a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">Status</a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">Writers</a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">Blog</a>
    </li>
  </ul>
</footer>

djblogger/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand fs-3" style="font-family: 'Archivo', sans-serif;
                  letter-spacing: -1.5px" href="#">djblogger</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

djblogger/templates/secondary-navbar.html
<style>
  #sm-logo-out {
    position: relative;
    background-color: black;
    width: 38px;
    height: 38px;
    top: 50%
  }

  #sm-logo-in {
    position: relative;
    background-color: white;
    width: 12px;
    height: 12px;
    top: 18%;
    left: 50%;
  }

  @media only screen and (max-width: 768px) {

    .container,
    .container-sm {
      max-width: 100%;
    }
  }

</style>
<nav class="navbar navbar-expand-lg py-1 align-items-start pt-lg-4 sticky-top">
  <div class="container py-2  sticky-top">
    <a href="{% url 'blog:home' %}" class="navbar-brand m-0">
      <div id="sm-logo-out">
        <div id="sm-logo-in"></div>
      </div>
    </a>
  </div>
</nav>